### ISSUE TITLE
[thotblock.js] @connect needs to be domain, not URL (at least for tampermonkey)

### ISSUE THREAD

**Issue by trinityd** [if-otherwise/violentmonkey-scripts#1]
On firefox dev edition, using tampermonkey. Maybe this isn't an issue on violentmonkey?

The line 

> // @connect     https://gist.githubusercontent.com

Results in tampermonkey refusing to connect, see this:

https://stackoverflow.com/questions/40979984/connect-tag-not-working-in-tampermonkey

If it's changed to 

> // @connect     gist.githubusercontent.com

we gucci

**Comment by if-otherwise** [comment]
Yeah I exclusively use/tested on violentmonkey, where it works fine. I just tried as @connect gist.githubusercontent.com and it works as well, so I'll go ahead and change it to that to increase support.
